import { CollectiveInfo } from "pages/CollectiveDetails/types";

export const popularCollectives: CollectiveInfo[] = [
  {
    collectiveID: 1,
    bannerImg: "https://source.unsplash.com/random/400x500?sig=10",
    iconImg: "https://source.unsplash.com/random/400x500?sig=10",
    collectiveName: "Sandbox",
    collectiveTicker: "Sandbox Ticker",
    shortDescription: "",
    category: {
      value: "gaming",
      label: "Gaming",
    },
    collectiveType: {
      value: "gaming",
      label: "Gaming",
    },
    links: [],
    details: "",
    projects: [],
  },
  {
    collectiveID: 2,
    bannerImg: "https://source.unsplash.com/random/400x500?sig=11",
    iconImg: "https://source.unsplash.com/random/400x500?sig=11",
    collectiveName: "World of Women Galaxy",
    collectiveTicker: "Sandbox Ticker",
    shortDescription: "",
    category: {
      value: "art",
      label: "Art",
    },
    collectiveType: {
      value: "art",
      label: "Art",
    },
    links: [],
    details: "",
    projects: [],
  },
  {
    collectiveID: 3,
    bannerImg: "https://source.unsplash.com/random/400x500?sig=12",
    iconImg: "https://source.unsplash.com/random/400x500?sig=12",
    collectiveName: "Doodles",
    collectiveTicker: "Doodles Ticker",
    shortDescription: "",
    category: {
      value: "art",
      label: "Art",
    },
    collectiveType: {
      value: "art",
      label: "Art",
    },
    links: [],
    details: "",
    projects: [],
  },
  {
    collectiveID: 4,
    bannerImg: "https://source.unsplash.com/random/400x500?sig=13",
    iconImg: "https://source.unsplash.com/random/400x500?sig=13",
    collectiveName: "Good Karma Records",
    collectiveTicker: "Ticker",
    shortDescription: "",
    category: {
      value: "music",
      label: "Music",
    },
    collectiveType: {
      value: "music",
      label: "Music",
    },
    links: [],
    details: "",
    projects: [],
  },
  {
    collectiveID: 5,
    bannerImg: "https://source.unsplash.com/random/400x500?sig=14",
    iconImg: "https://source.unsplash.com/random/400x500?sig=14",
    collectiveName: "Adam Bomb Squad",
    collectiveTicker: "Ticker",
    shortDescription: "",
    category: {
      value: "gaming",
      label: "Gaming",
    },
    collectiveType: {
      value: "gaming",
      label: "Gaming",
    },
    links: [],
    details: "",
    projects: [],
  },
  {
    collectiveID: 1,
    bannerImg: "https://source.unsplash.com/random/400x500?sig=15",
    iconImg: "https://source.unsplash.com/random/400x500?sig=15",
    collectiveName: "Sandbox",
    collectiveTicker: "Sandbox Ticker",
    shortDescription: "",
    category: {
      value: "gaming",
      label: "Gaming",
    },
    collectiveType: {
      value: "gaming",
      label: "Gaming",
    },
    links: [],
    details: "",
    projects: [],
  },
  {
    collectiveID: 2,
    bannerImg: "https://source.unsplash.com/random/400x500?sig=16",
    iconImg: "https://source.unsplash.com/random/400x500?sig=16",
    collectiveName: "World of Women Galaxy",
    collectiveTicker: "Sandbox Ticker",
    shortDescription: "",
    category: {
      value: "art",
      label: "Art",
    },
    collectiveType: {
      value: "art",
      label: "Art",
    },
    links: [],
    details: "",
    projects: [],
  },
  {
    collectiveID: 3,
    bannerImg: "https://source.unsplash.com/random/400x500?sig=17",
    iconImg: "https://source.unsplash.com/random/400x500?sig=17",
    collectiveName: "Doodles",
    collectiveTicker: "Doodles Ticker",
    shortDescription: "",
    category: {
      value: "art",
      label: "Art",
    },
    collectiveType: {
      value: "art",
      label: "Art",
    },
    links: [],
    details: "",
    projects: [],
  },
  {
    collectiveID: 4,
    bannerImg: "https://source.unsplash.com/random/400x500?sig=18",
    iconImg: "https://source.unsplash.com/random/400x500?sig=18",
    collectiveName: "Good Karma Records",
    collectiveTicker: "Ticker",
    shortDescription: "",
    category: {
      value: "music",
      label: "Music",
    },
    collectiveType: {
      value: "music",
      label: "Music",
    },
    links: [],
    details: "",
    projects: [],
  },
  {
    collectiveID: 5,
    bannerImg: "https://source.unsplash.com/random/400x500?sig=19",
    iconImg: "https://source.unsplash.com/random/400x500?sig=19",
    collectiveName: "Adam Bomb Squad",
    collectiveTicker: "Ticker",
    shortDescription: "",
    category: {
      value: "gaming",
      label: "Gaming",
    },
    collectiveType: {
      value: "gaming",
      label: "Gaming",
    },
    links: [],
    details: "",
    projects: [],
  },
];
